schema_version: 1

calibration_profiles:
  pressure_transducers:
    v_to_psi_0p5_4p5V_0_500psi:
      units: psi
      type: volts_to_psi
      v_min: 0.5
      v_max: 4.5
      psi_min: 0.0
      psi_max: 1000.0

    v_to_psi_0p5_4p5V_0_3000psi:
      units: psi
      type: volts_to_psi
      v_min: 0.5
      v_max: 4.5
      psi_min: 0.0
      psi_max: 3000.0
    
    v_to_psi_0p5_4p5V_0_80psi:
      units: psi
      type: volts_to_psi
      v_min: 0.5
      v_max: 4.5
      psi_min: 0.0
      psi_max: 80.0

  load_cells:
    # force_n = (|V_plus - V_minus| / excitation_voltage) / sensitivity_v_per_v * max_load_n - offset_n
    # where sensitivity_v_per_v is in V/V at full-scale load.
    engine_load_cell:
      units: N
      type: vdiff_to_force
      max_load_n: 980.67
      excitation_voltage: 10.0
      sensitivity_v_per_v: 0.002
      offset_n: 0.0

    nitrous_load_cell:
      units: N
      type: vdiff_to_force
      max_load_n: 980.67
      excitation_voltage: 10.0
      sensitivity_v_per_v: 0.002
      offset_n: 0.0

  rtds:
    pt1000_water_inlet:
      units: C
      type: rtd_callendar_van_dusen
      r0_ohms: 1000.0
      rref_ohms: 5576.0
      reference_factor: 2.0
      idac_current_ua: 100.0
      unit: "°C"
      offset: 0.0

    pt1000_water_outlet:
      units: C
      type: rtd_callendar_van_dusen
      r0_ohms: 1000.0
      rref_ohms: 5590.0
      reference_factor: 2.0
      idac_current_ua: 100.0
      unit: "°C"
      offset: 0.0

    nitrous_rtd:
      units: C
      type: rtd_callendar_van_dusen
      r0_ohms: 1000.0
      rref_ohms: 5587.0
      reference_factor: 2.0
      idac_current_ua: 100.0
      unit: "°C"
      offset: 0.0

  flow_meters:
    v_to_gpm_linear:
      units: gallons_per_minute
      type: linear
      v_min: 0.8 # 4mA over 200 ohm resistor
      v_max: 4 # 20mA over 200 ohm resistor
      gpm_min: 0.0
      gpm_max: 10

calibration:
  pressure_transducers:
    LF-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    FT-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    FM-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    FI-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    WM-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    CC-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    XF-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    OT-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    OF-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    OM-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    OI-PT: { profile: v_to_psi_0p5_4p5V_0_1000psi }
    IC-PT1: { profile: v_to_psi_0p5_4p5V_0_80psi }
    IC-PT2: { profile: v_to_psi_0p5_4p5V_0_80psi }
    IC-PT3: { profile: v_to_psi_0p5_4p5V_0_80psi }
    IC-PT4: { profile: v_to_psi_0p5_4p5V_0_80psi }
    IC-PT5: { profile: v_to_psi_0p5_4p5V_0_80psi }
    IC-PT6: { profile: v_to_psi_0p5_4p5V_0_80psi }

  load_cells:
    E-LC: { profile: engine_load_cell }
    N-LC: { profile: nitrous_load_cell }

  flow_meters:
    FM-FM: { profile: v_to_gpm_linear }
    OM-FM: { profile: v_to_gpm_linear }

  rtds:
    WI-RTD: { profile: pt1000_water_inlet }
    WO-RTD: { profile: pt1000_water_outlet }
    NT-RTD: { profile: nitrous_rtd }

limits:
  pressure_transducers:
    LF-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null

    FT-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null

    FM-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null

    FI-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null

    WM-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null

    CC-PT:
      green_max_psi: 450
      warn_max_psi: 500
      hard_abort_psi: 525
      hard_abort_min_psi: null


gui:
  pressure_rate_units: psi_per_min

