schema_version: 1

adcs:
  ADC1:
    model: ADS124S08IRHBT
    transport: spi
    spi_bus: 0
    spi_device: 0
    cs_gpio: null
    drdy_gpio: 25
    start_sync_gpio: 13
    notes: "ADC #1"

  ADC2:
    model: ADS124S08IRHBT
    transport: spi
    spi_bus: 0
    spi_device: 1
    cs_gpio: null
    drdy_gpio: 5
    start_sync_gpio: 26
    notes: "ADC #2"

  ADC3:
    model: ADS124S08IRHBT
    transport: spi
    spi_bus: 0
    spi_device: 0
    cs_gpio: 16
    drdy_gpio: 6
    start_sync_gpio: 20
    notes: "ADC #3"

sensors:
  pressure_transducers:
    LF-PT:
      enabled: true
      adc_id: ADC2
      signal_mode: single_ended
      pt_num: 1
      ain: 1
      sampling_rate_hz: 100
      notes: "L Fuel pressure transducer"

    FT-PT:
      enabled: true
      adc_id: ADC2
      signal_mode: single_ended
      ain: 0
      pt_num: 2
      sampling_rate_hz: 100
      notes: "Fuel tank pressure transducer"

    FM-PT:
      enabled: true
      adc_id: ADC2
      signal_mode: single_ended
      ain: 11
      pt_num: 3
      sampling_rate_hz: 100
      notes: "Fuel main pressure transducer"

    FI-PT:
      enabled: true
      adc_id: ADC2
      signal_mode: single_ended
      ain: 10
      pt_num: 4
      sampling_rate_hz: 100
      notes: "Fuel injector pressure transducer"

    WM-PT:
      enabled: true
      adc_id: ADC3
      signal_mode: single_ended
      ain: 9
      pt_num: 5
      sampling_rate_hz: 100
      notes: "Water main pressure transducer"

    CC-PT:
      enabled: true
      adc_id: ADC3
      signal_mode: single_ended
      ain: 8
      pt_num: 6
      sampling_rate_hz: 100
      notes: "Combustion chamber pressure transducer"

  resistive temperature detectors:
    WI-RTD:
      enabled: true
      adc_id: ADC1
      signal_mode: rtd_3_wire
      lead1_ain: 4
      lead2_ain: 2
      idac1_ain: 5
      idac2_ain: 3
      sampling_rate_hz: 10
      notes: "Water inlet RTD"
    
    WO-RTD:
      enabled: true
      adc_id: ADC2
      signal_mode: rtd_3_wire
      lead1_ain: 4
      lead2_ain: 2
      idac1_ain: 5
      idac2_ain: 3
      sampling_rate_hz: 10
      notes: "Water outlet RTD"
    
  load cells:
    E-LC:
      enabled: true
      adc_id: ADC1
      signal_mode: differential
      ain_pos: null
      ain_neg: null
      sampling_rate_hz: 100
      notes: "Engine thrust load cell"

    N-LC:
      enabled: true
      adc_id: ADC2
      signal_mode: differential
      ain_pos: null
      ain_neg: null
      sampling_rate_hz: 100
      notes: "Nitrous load cell"
    
  flow meters:
    FM-FM:
      enabled: true
      adc_id: ADC3
      signal_mode: single_ended
      ain: null
      sampling_rate_hz: 100
      notes: "Fuel main flow meter"

    OM-FM:
      enabled: true
      adc_id: ADC3
      signal_mode: single_ended
      ain: null
      sampling_rate_hz: 100
      notes: "Oxidizer main flow meter"
    

actuators:
  valves:
    wmv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Water main valve"

    ftvv:
      enabled: true
      mode: on_off
      pin: null
      active_high: false
      notes: "Fuel tank vent valve"

    fmv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Fuel main valve"

    fmctv:
      enabled: true
      mode: throttle
      pin: null
      active_high: true
      notes: "Fuel main control/throttle valve"

    fifv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Fuel igniter flow valve"

    lffv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Pressurant fuel filling flow valve"

    xffv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Pressurant oxidizer filling flow valve"

    offv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Oxidizer filling flow valve"

    omv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Oxidizer main valve"

    omctv:
      enabled: true
      mode: throttle
      pin: null
      active_high: true
      notes: "Oxidizer main control/throttle valve"

    otvv:
      enabled: true
      mode: on_off
      pin: null
      active_high: false
      notes: "Oxidizer tank vent valve"

    oifv:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Oxidizer igniter flow valve"

    sparker:
      enabled: true
      mode: on_off
      pin: null
      active_high: true
      notes: "Igniter sparker"