sequences:
  - name: fill
    steps:
      - valve_id: ftvv
        action: closed
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: otvv
        action: closed
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: lffv
        action: open
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: lffv
        action: closed
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: otvv
        action: open
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: offv
        action: open
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: offv
        action: close
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: otvv
        action: close
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: ftfv
        action: open
        time_delay: 0.0
        user_input: true
        system_state: fill

      - valve_id: otfv
        action: open
        time_delay: 0.0
        user_input: true
        system_state: fill

  - name: fire
    steps:
      - valve_id: wmv
        angle: 90.0
        time_delay: 0.0
        user_input: false
        system_state: fire

      - valve_id: igniter
        action: open
        time_delay: 0.0
        user_input: false
        system_state: fire

      - valve_id: fifv
        action: open
        time_delay: 0.0
        user_input: false
        system_state: fire

      - valve_id: oifv
        action: open
        time_delay: 2.0
        user_input: false
        system_state: fire

      - valve_id: omctv
        angle: 90.0
        time_delay: 0.0
        user_input: false
        system_state: fire

      - valve_id: fmctv
        angle: 90.0
        time_delay: 2.0
        user_input: false
        system_state: throttle

      - valve_id: fifv
        action: closed
        time_delay: 0.0
        user_input: false
        system_state: throttle

      - valve_id: oifv
        action: closed
        time_delay: 2.0
        user_input: false
        system_state: throttle

      - valve_id: sparker
        action: closed
        time_delay: 4.0
        user_input: false
        system_state: throttle

      - valve_id: lffv
        action: closed
        time_delay: 0.0
        user_input: false
        system_state: fire

      - valve_id: xffv
        action: closed
        time_delay: 0.0
        user_input: true
        system_state: fire