sequences:
  - name: fire
    steps:
      - valve_id: omv
        action: open
        time_delay: 0.0
        user_input: false
        condition_valve: xffv
        condition_state: open
        system_state: fire

      - valve_id: fmv
        action: open
        time_delay: 0.0
        user_input: true
        condition_valve: omv
        condition_state: open
        system_state: fire

      - valve_id: wmv
        action: open
        time_delay: 0.0
        user_input: false
        condition_valve: fmv
        condition_state: open
        system_state: fire

      - valve_id: igniter
        action: open
        time_delay: 0.0
        user_input: false
        condition_valve: wmv
        condition_state: open
        system_state: fire

      - valve_id: fifv
        action: open
        time_delay: 0.0
        user_input: false
        condition_valve: wmv
        condition_state: open
        system_state: fire

      - valve_id: oifv
        action: open
        time_delay: 2.0
        user_input: false
        condition_valve: fifv
        condition_state: open
        system_state: fire

      - valve_id: omctv
        action: open
        time_delay: 0.0
        user_input: false
        condition_valve: oifv
        condition_state: open
        system_state: fire

      - valve_id: fmctv
        action: open
        time_delay: 2.0
        user_input: false
        condition_valve: omctv
        condition_state: open
        system_state: throttle

      - valve_id: fifv
        action: close
        time_delay: 0.0
        user_input: false
        condition_valve: wmv
        condition_state: open
        system_state: fire

      - valve_id: oifv
        action: close
        time_delay: 2.0
        user_input: false
        condition_valve: fifv
        condition_state: open
        system_state: fire

      - valve_id: sparker
        action: close
        time_delay: 0.0
        user_input: false
        condition_valve: oifv
        condition_state: close
        system_state: fire

      - valve_id: lffv
        action: close
        time_delay: 0.0
        user_input: false
        condition_valve: igniter
        condition_state: close
        system_state: fire

      - valve_id: xffv
        action: close
        time_delay: 0.0
        user_input: true
        condition_valve: lffv
        condition_state: close
        system_state: fire