actuators:
  valves:
    wmv:
      enabled: true
      mode: on_off
      pin: 1
      normally_closed: true
      notes: "Water main valve"

    ftvv:
      enabled: true
      mode: on_off
      pin: 2
      normally_closed: false
      notes: "Fuel tank vent valve"

    fmv:
      enabled: true
      mode: on_off
      pin: 3
      normally_closed: true
      notes: "Fuel main valve"

    fifv:
      enabled: true
      mode: on_off
      pin: 4
      normally_closed: true
      notes: "Fuel igniter flow valve"

    lffv:
      enabled: true
      mode: on_off
      pin: 5
      normally_closed: true
      notes: "Pressurant fuel filling flow valve"

    xffv:
      enabled: true
      mode: on_off
      pin: 6
      normally_closed: true
      notes: "Pressurant oxidizer filling flow valve"

    offv:
      enabled: true
      mode: on_off
      pin: 7
      normally_closed: true
      notes: "Oxidizer filling flow valve"

    omv:
      enabled: true
      mode: on_off
      pin: 8
      normally_closed: true
      notes: "Oxidizer main valve"

    otvv:
      enabled: true
      mode: on_off
      pin: 9
      normally_closed: false
      notes: "Oxidizer tank vent valve"

    oifv:
      enabled: true
      mode: on_off
      pin: 10
      normally_closed: true
      notes: "Oxidizer igniter flow valve"

    sparker:
      enabled: true
      mode: on_off
      pin: 11
      normally_closed: true
      notes: "Igniter sparker"