actuators:
  valves:
    test_valve1:
      enabled: true
      mode: on_off
      pin: 1
      normally_closed: true
      notes: "Test valve 1"

    test_valve2:
      enabled: true
      mode: on_off
      pin: 2
      normally_closed: true
      notes: "Fuel tank vent valve"

    test_valve3:
      enabled: true
      mode: on_off
      pin: 3
      normally_closed: true
      notes: "Fuel main valve"

    test_valve4:
      enabled: true
      mode: on_off
      pin: 4
      normally_closed: true
      notes: "Fuel igniter flow valve"

    test_valve5:
      enabled: true
      mode: on_off
      pin: 5
      normally_closed: true
      notes: "Pressurant fuel filling flow valve"

    test_valve6:
      enabled: true
      mode: on_off
      pin: 6
      normally_closed: true
      notes: "Pressurant oxidizer filling flow valve"

    test_valve7:
      enabled: true
      mode: on_off
      pin: 7
      normally_closed: true
      notes: "Oxidizer filling flow valve"

    test_valve8:
      enabled: true
      mode: on_off
      pin: 8
      normally_closed: true
      notes: "Oxidizer main valve"

    test_valve9:
      enabled: true
      mode: on_off
      pin: 9
      normally_closed: false
      notes: "Oxidizer tank vent valve"

    test_valve10:
      enabled: true
      mode: on_off
      pin: 10
      normally_closed: true
      notes: "Oxidizer igniter flow valve"